services:
  caddy:
    container_name: caddy
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    networks:
      - caddy-bridge
  hono-api:
    depends_on:
      - caddy
    container_name: hono-api
    build: .
    ports:
      - "4587:4587"
    environment:
      - PORT=4587
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Caddyfile:/app/Caddyfile
    networks:
      - caddy-bridge

networks:
  caddy-bridge:

volumes:
  caddy_data:
  caddy_config:
